import { ParsedAsset } from "./parser";

export function compileTemplate(text: string): string {
  const escaped = text
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\${/g, "\\${");

  const hasPlaceholders = /\{([^}]+)\}/.test(escaped);
  if (!hasPlaceholders) {
    return `() => \`${escaped}\``;
  }

  const compiled = escaped.replace(/\{([^}]+)\}/g, (_, key) => {
    return `\${params.${key.trim()}}`;
  });

  return `(params: any) => \`${compiled}\``;
}

export function generateGlobalLocale(locale: string, assets: ParsedAsset[]): string {
  const localeAssets = assets.filter(a => a.locale === locale && (a.type === "backend" || a.type === "frontend-global"));
  
  const lines: string[] = [];
  lines.push("/* eslint-disable */");
  lines.push("// Auto-generated by @skalfa/skalfa-cli. Do not edit manually.");
  lines.push("import type { Lang } from \"../types\";");
  lines.push("");
  lines.push(`export const ${locale}: Lang = {`);

  const namespaces: Record<string, Record<string, string>> = {};
  for (const asset of localeAssets) {
    const ns = asset.namespace;
    if (!namespaces[ns]) {
      namespaces[ns] = {};
    }
    for (const [key, value] of Object.entries(asset.content)) {
      namespaces[ns][key] = value;
    }
  }

  for (const [ns, contentMap] of Object.entries(namespaces)) {
    lines.push(`  ${ns}: {`);
    for (const [key, val] of Object.entries(contentMap)) {
      lines.push(`    ${key}: ${compileTemplate(val)},`);
    }
    lines.push(`  },`);
  }

  lines.push("};");
  lines.push(`export default ${locale};`);

  return lines.join("\n") + "\n";
}

export function generateModuleLocale(moduleName: string, assets: ParsedAsset[]): string {
  const moduleAssets = assets.filter(a => a.moduleName === moduleName && a.type === "frontend-module");

  const lines: string[] = [];
  lines.push("/* eslint-disable */");
  lines.push("// Auto-generated by @skalfa/skalfa-cli. Do not edit manually.");
  lines.push("");
  lines.push("export default {");

  const localeMap: Record<string, Record<string, Record<string, string>>> = {};
  for (const asset of moduleAssets) {
    const loc = asset.locale;
    const ns = asset.namespace;
    if (!localeMap[loc]) {
      localeMap[loc] = {};
    }
    if (!localeMap[loc][ns]) {
      localeMap[loc][ns] = {};
    }
    for (const [key, value] of Object.entries(asset.content)) {
      localeMap[loc][ns][key] = value;
    }
  }

  for (const [loc, nsMap] of Object.entries(localeMap)) {
    lines.push(`  ${loc}: {`);
    for (const [ns, contentMap] of Object.entries(nsMap)) {
      lines.push(`    ${ns}: {`);
      for (const [key, val] of Object.entries(contentMap)) {
        lines.push(`      ${key}: ${compileTemplate(val)},`);
      }
      lines.push(`    },`);
    }
    lines.push(`  },`);
  }

  lines.push("};");

  return lines.join("\n") + "\n";
}

export function generateManifest(locales: string[], modules: string[]): string {
  const lines: string[] = [];
  lines.push("/* eslint-disable */");
  lines.push("// Auto-generated by @skalfa/skalfa-cli. Do not edit manually.");
  lines.push("");
  lines.push("export const manifest = {");
  lines.push(`  locales: ${JSON.stringify(locales)} as const,`);
  lines.push("  modules: {");
  for (const mod of modules) {
    const filename = mod.replace(/\//g, ".");
    lines.push(`    "${mod}": () => import("./modules/${filename}"),`);
  }
  lines.push("  },");
  lines.push("};");
  lines.push("export default manifest;");

  return lines.join("\n") + "\n";
}

export function generateIndex(locales: string[]): string {
  const lines: string[] = [];
  lines.push("/* eslint-disable */");
  lines.push("// Auto-generated by @skalfa/skalfa-cli. Do not edit manually.");
  lines.push("");
  lines.push("export * from \"./types\";");
  lines.push("export * from \"./manifest\";");
  for (const loc of locales) {
    lines.push(`export { default as ${loc} } from \"./locales/${loc}\";`);
  }
  lines.push("");

  return lines.join("\n") + "\n";
}
