import { ParsedAsset } from "./parser";
import { extractPlaceholders } from "./placeholder";

export function generateTypes(assets: ParsedAsset[], defaultLocale: string = "id"): string {
  const globalAssets = assets.filter(a => a.type === "backend" || a.type === "frontend-global");
  const moduleAssets = assets.filter(a => a.type === "frontend-module");

  const globalNamespaces: Record<string, Record<string, string[]>> = {};

  const processAsset = (asset: ParsedAsset, targetMap: Record<string, Record<string, string[]>>) => {
    const ns = asset.namespace;
    if (!targetMap[ns]) {
      targetMap[ns] = {};
    }
    for (const [key, value] of Object.entries(asset.content)) {
      if (!targetMap[ns][key]) {
        targetMap[ns][key] = extractPlaceholders(value);
      }
    }
  };

  globalAssets.filter(a => a.locale === defaultLocale).forEach(a => processAsset(a, globalNamespaces));
  globalAssets.filter(a => a.locale !== defaultLocale).forEach(a => processAsset(a, globalNamespaces));

  const modulesMap: Record<string, Record<string, Record<string, string[]>>> = {};

  const processModuleAsset = (asset: ParsedAsset) => {
    const mod = asset.moduleName || "";
    const ns = asset.namespace;
    if (!modulesMap[mod]) {
      modulesMap[mod] = {};
    }
    if (!modulesMap[mod][ns]) {
      modulesMap[mod][ns] = {};
    }
    for (const [key, value] of Object.entries(asset.content)) {
      if (!modulesMap[mod][ns][key]) {
        modulesMap[mod][ns][key] = extractPlaceholders(value);
      }
    }
  };

  moduleAssets.filter(a => a.locale === defaultLocale).forEach(processModuleAsset);
  moduleAssets.filter(a => a.locale !== defaultLocale).forEach(processModuleAsset);

  const lines: string[] = [];

  lines.push("/* eslint-disable */");
  lines.push("// This file was auto-generated by @skalfa/skalfa-cli. Do not edit manually.");
  lines.push("");

  const formatNamespace = (keysMap: Record<string, string[]>, indent: string = "    "): string[] => {
    const res: string[] = [];
    for (const [key, placeholders] of Object.entries(keysMap)) {
      if (placeholders.length === 0) {
        res.push(`${indent}${key}(): string;`);
      } else {
        const paramsType = placeholders.map(p => `${p}: string | number`).join("; ");
        res.push(`${indent}${key}(params: { ${paramsType} }): string;`);
      }
    }
    return res;
  };

  lines.push("export interface Lang {");
  for (const [ns, keysMap] of Object.entries(globalNamespaces)) {
    lines.push(`  ${ns}: {`);
    lines.push(...formatNamespace(keysMap, "    "));
    lines.push(`  };`);
  }
  lines.push("}");
  lines.push("");

  lines.push("export interface ModuleLangs {");
  for (const [mod, namespaces] of Object.entries(modulesMap)) {
    lines.push(`  "${mod}": {`);
    for (const [ns, keysMap] of Object.entries(namespaces)) {
      lines.push(`    ${ns}: {`);
      lines.push(...formatNamespace(keysMap, "      "));
      lines.push(`    };`);
    }
    lines.push(`  };`);
  }
  lines.push("}");
  lines.push("");

  lines.push("declare module \"@skalfa/skalfa-lang\" {");
  lines.push("  export function useLang(): Lang;");
  lines.push("  export function useLang<K extends keyof ModuleLangs>(moduleName: K): Lang & ModuleLangs[K];");
  lines.push("}");

  return lines.join("\n") + "\n";
}
